'use client'

import { useState } from 'react'
import { ForgeResult } from './ForgeCard'

const PRE_COMMIT_SH = `#!/bin/bash
# pre-commit.sh
# Generated by CLAUDE.md Forge — claudemdforge.site

echo "🔨 Running pre-commit quality checks..."

# TypeScript type check
npx tsc --noEmit
[ $? -ne 0 ] && echo "❌ TypeScript errors found." && exit 1

# ESLint check
npx eslint . --ext .ts,.tsx --max-warnings 0
[ $? -ne 0 ] && echo "❌ Lint errors found." && exit 1

# Unit tests
npx vitest run
[ $? -ne 0 ] && echo "❌ Tests failed." && exit 1

echo "✓ All checks passed."`

const SETUP_GUIDE = `# SETUP GUIDE — claudemdforge.site

## 1 — Place files in your project
cp CLAUDE.md /your-project/CLAUDE.md
cp -r skills/ /your-project/.claude/skills/

## 2 — Enable the pre-commit hook (optional)
chmod +x hooks/pre-commit.sh
cp hooks/pre-commit.sh .git/hooks/pre-commit

## 3 — Open Claude Code
claude   # Claude Code auto-reads CLAUDE.md on every session

# Files in this ZIP:
# CLAUDE.md              ← main AI context file
# skills/ (6-8 files)   ← curated skill instructions
# hooks/pre-commit.sh   ← quality gate automation
# SETUP_GUIDE.md        ← this file

---
Generated by CLAUDE.md Forge — claudemdforge.site`

type Tab = 'claude-md' | 'skills' | 'hooks' | 'setup'

type Props = {
  result: ForgeResult
}

function colorLine(line: string): { text: string; color: string } {
  if (line.startsWith('#')) return { text: line, color: '#E05C15' }
  if (line.startsWith('-')) return { text: line, color: '#A8D8A4' }
  if (line.startsWith('→')) return { text: line, color: '#7AB8F5' }
  if (line.startsWith('[Source')) return { text: line, color: '#666' }
  return { text: line, color: '#E6E4DC' }
}

function titleToFilename(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '') + '.md'
}

async function generateShareCaption(claudeMd: string, skills: ForgeResult['skills'], tags: string[]): Promise<string> {
  const snippet = claudeMd.slice(0, 600)
  const res = await fetch('/api/test-drive', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      messages: [
        {
          role: 'system',
          content: 'You are a developer tweet writer. Generate a single engaging tweet (under 220 characters) for a developer who just generated a custom CLAUDE.md setup. Mention the stack/skills if interesting. Include #ClaudeCode at the end. Output ONLY the tweet text — no quotes, no preamble.',
        },
        {
          role: 'user',
          content: `Stack detected: ${tags.join(', ')}\nSkills selected: ${skills.map(s => s.title).join(', ')}\n\nCLAUDE.md preview:\n${snippet}`,
        },
      ],
    }),
  })
  const data = await res.json()
  return (data.content as string) ?? `Just forged my perfect CLAUDE.md with ${skills.length} skills for ${tags.slice(0, 2).join(' + ')} — @claudemdforge #ClaudeCode`
}

export default function ResultPreview({ result }: Props) {
  const [activeTab, setActiveTab] = useState<Tab>('claude-md')
  const [copied, setCopied] = useState(false)
  const [sharing, setSharing] = useState(false)

  function downloadZip() {
    const url = URL.createObjectURL(result.zipBlob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'claude-forge-output.zip'
    a.click()
    URL.revokeObjectURL(url)
  }

  async function copyClaudeMd() {
    await navigator.clipboard.writeText(result.claudeMd)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  async function shareOnX() {
    setSharing(true)
    try {
      const caption = await generateShareCaption(result.claudeMd, result.skills, result.tags)
      const url = `https://twitter.com/intent/tweet?text=${encodeURIComponent(caption + '\n\nclaudemdforge.site')}`
      window.open(url, '_blank', 'noopener,noreferrer')
    } catch {
      const fallback = `Just forged my CLAUDE.md with ${result.skills.length} skills via claudemdforge.site — #ClaudeCode`
      window.open(`https://twitter.com/intent/tweet?text=${encodeURIComponent(fallback)}`, '_blank', 'noopener,noreferrer')
    } finally {
      setSharing(false)
    }
  }

  const tabs: { id: Tab; label: string }[] = [
    { id: 'claude-md', label: 'CLAUDE.md' },
    { id: 'skills', label: 'skills/' },
    { id: 'hooks', label: 'hooks/' },
    { id: 'setup', label: 'SETUP_GUIDE.md' },
  ]

  return (
    <div style={{ marginTop: 48 }}>
      <div className="result-wrap">
        <div className="result-header">
          <div className="success-dot" />
          <span style={{ fontWeight: 700, fontSize: 13.5, color: 'var(--green)' }}>Forge Complete</span>
          <span className="mono muted" style={{ fontSize: 12 }}>
            {result.skills.length} skills selected · {result.tags.slice(0, 3).join(' + ')}
          </span>
          <div style={{ flex: 1 }} />
          <button className="btn-dark" style={{ marginRight: 8 }} onClick={copyClaudeMd}>
            {copied ? '✓ Copied' : '📋 Copy CLAUDE.md'}
          </button>
          <button className="btn-primary" style={{ fontSize: 13, padding: '9px 18px' }} onClick={downloadZip}>
            ⬇ Download ZIP
          </button>
        </div>

        <div className="result-tabs">
          {tabs.map(tab => (
            <button
              key={tab.id}
              className={`result-tab${activeTab === tab.id ? ' active' : ''}`}
              onClick={() => setActiveTab(tab.id)}
            >
              {tab.label}
            </button>
          ))}
        </div>

        <div style={{ padding: 24 }}>
          {activeTab === 'claude-md' && (
            <div className="code-block">
              {result.claudeMd.split('\n').map((line, i) => {
                const { text, color } = colorLine(line)
                return (
                  <span key={i} style={{ color, display: 'block' }}>
                    {text || ' '}
                  </span>
                )
              })}
            </div>
          )}

          {activeTab === 'skills' && (
            <div style={{ display: 'flex', flexDirection: 'column', gap: 9 }}>
              {result.skills.map(skill => (
                <div
                  key={skill.id}
                  style={{
                    display: 'flex', alignItems: 'center', gap: 12,
                    padding: '11px 16px', background: 'var(--bg2)',
                    borderRadius: 9, border: '1px solid var(--border)',
                  }}
                >
                  <span style={{ fontSize: 14 }}>📄</span>
                  <span className="mono orange" style={{ fontSize: 12.5 }}>
                    {titleToFilename(skill.title)}
                  </span>
                  <div style={{ flex: 1 }} />
                  <span className="badge badge-cat">{skill.cat}</span>
                </div>
              ))}
            </div>
          )}

          {activeTab === 'hooks' && (
            <div className="code-block">{PRE_COMMIT_SH}</div>
          )}

          {activeTab === 'setup' && (
            <div className="code-block">{SETUP_GUIDE}</div>
          )}
        </div>
      </div>

      <div className="share-box">
        <span style={{ fontSize: 20 }}>𝕏</span>
        <div style={{ flex: 1 }}>
          <div style={{ fontSize: 13.5, fontWeight: 600, marginBottom: 2 }}>Share your forge</div>
          <div style={{ fontSize: 12.5, color: 'var(--muted)' }}>
            {sharing ? 'Claude is writing your tweet…' : 'Help other developers find this tool — every share matters.'}
          </div>
        </div>
        <button
          className="btn-outline"
          style={{ fontSize: 13, padding: '9px 18px', whiteSpace: 'nowrap', opacity: sharing ? 0.6 : 1 }}
          onClick={shareOnX}
          disabled={sharing}
        >
          {sharing ? 'Generating…' : 'Share on X →'}
        </button>
      </div>
    </div>
  )
}
