'use client'

import { useState } from 'react'
import { ForgeResult } from './ForgeCard'

const PRE_COMMIT_SH = `#!/bin/bash
# pre-commit.sh — Generated by CLAUDE.md Forge

echo "🔨 Running pre-commit quality checks..."

npx tsc --noEmit
[ $? -ne 0 ] && echo "❌ TypeScript errors found." && exit 1

npx eslint . --ext .ts,.tsx --max-warnings 0
[ $? -ne 0 ] && echo "❌ Lint errors found." && exit 1

npx vitest run
[ $? -ne 0 ] && echo "❌ Tests failed." && exit 1

echo "✓ All checks passed."`

const SETUP_GUIDE = `# SETUP GUIDE — claudemdforge.site

## 1 — Place files in your project
cp CLAUDE.md /your-project/CLAUDE.md
cp -r skills/ /your-project/.claude/skills/

## 2 — Enable the pre-commit hook (optional)
chmod +x hooks/pre-commit.sh
cp hooks/pre-commit.sh .git/hooks/pre-commit

## 3 — Open Claude Code
claude   # Claude Code auto-reads CLAUDE.md on every session

---
Generated by CLAUDE.md Forge — claudemdforge.site`

type Props = { result: ForgeResult }

function toSlug(title: string) {
  return title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') + '.md'
}

function colorLine(line: string): string {
  if (line.startsWith('#')) return '#E05C15'
  if (line.startsWith('-') || line.startsWith('*')) return '#A8D8A4'
  if (line.startsWith('→')) return '#7AB8F5'
  if (line.startsWith('[Source')) return '#555'
  return '#E6E4DC'
}

async function generateShareCaption(claudeMd: string, skills: ForgeResult['skills'], tags: string[]): Promise<string> {
  const res = await fetch('/api/test-drive', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      messages: [
        { role: 'system', content: 'You are a developer tweet writer. Generate a single engaging tweet (under 220 characters) for a developer who just generated a custom CLAUDE.md setup. Mention the stack/skills if interesting. Include #ClaudeCode at the end. Output ONLY the tweet text — no quotes, no preamble.' },
        { role: 'user', content: `Stack: ${tags.join(', ')}\nSkills: ${skills.map(s => s.title).join(', ')}\n\nCLAUDE.md preview:\n${claudeMd.slice(0, 500)}` },
      ],
    }),
  })
  const data = await res.json()
  return (data.content as string) ?? `Just forged my perfect CLAUDE.md with ${skills.length} skills for ${tags.slice(0, 2).join(' + ')} — claudemdforge.site #ClaudeCode`
}

type FileEntry = { id: string; icon: string; label: string; lang?: string; content: string }

export default function ResultPreview({ result }: Props) {
  const [activeId, setActiveId] = useState('claude-md')
  const [copied, setCopied] = useState(false)
  const [sharing, setSharing] = useState(false)

  const files: FileEntry[] = [
    { id: 'claude-md', icon: '🟠', label: 'CLAUDE.md', lang: 'markdown', content: result.claudeMd },
    ...result.skills.map(s => ({
      id: `skill-${s.id}`,
      icon: '📄',
      label: toSlug(s.title),
      lang: 'markdown',
      content: s.snippet,
    })),
    { id: 'hook', icon: '🔧', label: 'pre-commit.sh', lang: 'bash', content: PRE_COMMIT_SH },
    { id: 'setup', icon: '📋', label: 'SETUP_GUIDE.md', lang: 'markdown', content: SETUP_GUIDE },
  ]

  const active = files.find(f => f.id === activeId) ?? files[0]

  function downloadZip() {
    const url = URL.createObjectURL(result.zipBlob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'claude-forge-output.zip'
    a.click()
    URL.revokeObjectURL(url)
  }

  async function copyActive() {
    await navigator.clipboard.writeText(active.content)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  async function shareOnX() {
    setSharing(true)
    try {
      const caption = await generateShareCaption(result.claudeMd, result.skills, result.tags)
      window.open(`https://twitter.com/intent/tweet?text=${encodeURIComponent(caption + '\n\nclaudemdforge.site')}`, '_blank', 'noopener,noreferrer')
    } catch {
      const fallback = `Just forged my CLAUDE.md with ${result.skills.length} skills via claudemdforge.site — #ClaudeCode`
      window.open(`https://twitter.com/intent/tweet?text=${encodeURIComponent(fallback)}`, '_blank', 'noopener,noreferrer')
    } finally {
      setSharing(false)
    }
  }

  return (
    <div style={{ marginTop: 48 }}>

      {/* Success banner */}
      <div style={{
        display: 'flex', alignItems: 'center',
        padding: '14px 20px', marginBottom: 2,
        background: 'linear-gradient(135deg, #F0FDF4 0%, #ECFDF5 100%)',
        border: '1px solid #BBF7D0', borderRadius: '14px 14px 0 0',
        flexWrap: 'wrap', gap: 10,
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <div style={{ width: 8, height: 8, borderRadius: '50%', background: '#22C55E', boxShadow: '0 0 0 3px rgba(34,197,94,0.2)' }} />
          <span style={{ fontFamily: 'var(--font-syne), Syne, sans-serif', fontWeight: 700, fontSize: 13.5, color: '#15803D' }}>
            Forge complete
          </span>
        </div>
        <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
          {[
            { v: `${files.length} files`, c: '#15803D', bg: '#DCFCE7', border: '#86EFAC' },
            { v: `${result.skills.length} skills`, c: '#1D4ED8', bg: '#EFF6FF', border: '#93C5FD' },
            ...result.tags.slice(0, 3).map(t => ({ v: t, c: 'var(--orange)', bg: 'var(--orange-light)', border: 'var(--orange-border)' })),
          ].map(chip => (
            <span key={chip.v} className="mono" style={{
              fontSize: 11, padding: '3px 9px', borderRadius: 5,
              background: chip.bg, border: `1px solid ${chip.border}`, color: chip.c,
            }}>{chip.v}</span>
          ))}
        </div>
        <div style={{ flex: 1 }} />
        <div style={{ display: 'flex', gap: 8 }}>
          <button className="btn-dark" onClick={copyActive}>
            {copied ? '✓ Copied' : `📋 Copy ${active.label}`}
          </button>
          <button className="btn-primary" style={{ fontSize: 13, padding: '9px 18px' }} onClick={downloadZip}>
            ⬇ Download ZIP
          </button>
        </div>
      </div>

      {/* IDE layout */}
      <div style={{
        display: 'grid', gridTemplateColumns: '220px 1fr',
        border: '1px solid var(--border)', borderTop: 'none',
        borderRadius: '0 0 14px 14px', overflow: 'hidden',
        background: 'var(--bg)',
        minHeight: 440,
      }}>
        {/* File tree sidebar */}
        <div style={{ borderRight: '1px solid var(--border)', background: 'var(--bg2)' }}>
          {/* Folder headers */}
          {[
            { label: 'claude-forge-output/', items: files.filter(f => f.id === 'claude-md') },
            { label: 'skills/', items: files.filter(f => f.id.startsWith('skill-')) },
            { label: 'hooks/', items: files.filter(f => f.id === 'hook') },
            { label: '', items: files.filter(f => f.id === 'setup') },
          ].map(group => (
            <div key={group.label}>
              {group.label && (
                <div style={{
                  padding: '7px 14px 4px',
                  fontSize: 10.5,
                  fontFamily: 'var(--font-dm-mono), DM Mono, monospace',
                  color: 'var(--faint)',
                  letterSpacing: 0.5,
                  userSelect: 'none',
                }}>
                  {group.label}
                </div>
              )}
              {group.items.map(f => (
                <button
                  key={f.id}
                  onClick={() => setActiveId(f.id)}
                  style={{
                    width: '100%', textAlign: 'left',
                    padding: '7px 14px 7px 22px',
                    display: 'flex', alignItems: 'center', gap: 7,
                    background: activeId === f.id ? 'var(--white)' : 'transparent',
                    borderLeft: activeId === f.id ? '2px solid var(--orange)' : '2px solid transparent',
                    border: 'none', cursor: 'pointer', transition: 'background 0.12s',
                    fontFamily: 'var(--font-dm-mono), DM Mono, monospace',
                    fontSize: 12, color: activeId === f.id ? 'var(--text)' : 'var(--muted)',
                    whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis',
                  }}
                >
                  <span style={{ fontSize: 13 }}>{f.icon}</span>
                  <span style={{ overflow: 'hidden', textOverflow: 'ellipsis' }}>{f.label}</span>
                </button>
              ))}
            </div>
          ))}
        </div>

        {/* Content pane */}
        <div style={{ display: 'flex', flexDirection: 'column', minWidth: 0 }}>
          {/* Tab bar */}
          <div style={{
            display: 'flex', alignItems: 'center', gap: 0,
            borderBottom: '1px solid var(--border)', background: 'var(--bg2)',
            padding: '0 16px', height: 36, flexShrink: 0,
          }}>
            <span style={{ fontSize: 12, fontFamily: 'var(--font-dm-mono), DM Mono, monospace', color: 'var(--muted)' }}>
              {active.icon} {active.label}
            </span>
            {active.lang && (
              <span className="mono" style={{ marginLeft: 'auto', fontSize: 10, color: 'var(--faint)', background: 'var(--bg3)', padding: '2px 7px', borderRadius: 4 }}>
                {active.lang}
              </span>
            )}
          </div>

          {/* Code area */}
          <div style={{ flex: 1, overflow: 'auto', padding: '18px 22px' }}>
            {active.id === 'claude-md' ? (
              <div style={{ fontFamily: 'var(--font-dm-mono), DM Mono, monospace', fontSize: 12.5, lineHeight: 1.85, whiteSpace: 'pre-wrap' }}>
                {result.claudeMd.split('\n').map((line, i) => (
                  <div key={i} style={{ color: colorLine(line) }}>{line || ' '}</div>
                ))}
              </div>
            ) : (
              <pre style={{
                fontFamily: 'var(--font-dm-mono), DM Mono, monospace',
                fontSize: 12.5, lineHeight: 1.85, margin: 0,
                color: '#E6E4DC', whiteSpace: 'pre-wrap', wordBreak: 'break-word',
              }}>
                {active.content}
              </pre>
            )}
          </div>

          {/* Status bar */}
          <div style={{
            borderTop: '1px solid var(--border)', background: 'var(--dark)',
            padding: '5px 16px', display: 'flex', alignItems: 'center', gap: 16, flexShrink: 0,
          }}>
            <span className="mono" style={{ fontSize: 10.5, color: '#444' }}>
              {active.content.split('\n').length} lines
            </span>
            <span className="mono" style={{ fontSize: 10.5, color: '#444' }}>
              {(active.content.length / 1024).toFixed(1)} kb
            </span>
            <div style={{ flex: 1 }} />
            <span className="mono" style={{ fontSize: 10.5, color: '#444' }}>
              UTF-8 · {active.lang ?? 'plaintext'}
            </span>
          </div>
        </div>
      </div>

      {/* Share strip */}
      <div className="share-box" style={{ marginTop: 16 }}>
        <span style={{ fontSize: 18, fontWeight: 700, fontFamily: 'serif' }}>𝕏</span>
        <div style={{ flex: 1 }}>
          <div style={{ fontSize: 13.5, fontWeight: 600, marginBottom: 2 }}>Share your forge</div>
          <div style={{ fontSize: 12.5, color: 'var(--muted)' }}>
            {sharing ? 'Claude is writing your tweet…' : 'Claude writes a custom caption from your CLAUDE.md — every share helps.'}
          </div>
        </div>
        <button
          className="btn-outline"
          style={{ fontSize: 13, padding: '9px 18px', whiteSpace: 'nowrap', opacity: sharing ? 0.6 : 1 }}
          onClick={shareOnX}
          disabled={sharing}
        >
          {sharing ? 'Generating…' : 'Share on X →'}
        </button>
      </div>
    </div>
  )
}
