'use client'

import { useState } from 'react'
import { createPortal } from 'react-dom'
import { ForgeResult } from './ForgeCard'
import { Skill } from '@/lib/skills'

const PRE_COMMIT_SH = `#!/bin/bash
# pre-commit.sh â€” Generated by CLAUDE.md Forge

echo "ðŸ”¨ Running pre-commit quality checks..."

npx tsc --noEmit
[ $? -ne 0 ] && echo "âŒ TypeScript errors found." && exit 1

npx eslint . --ext .ts,.tsx --max-warnings 0
[ $? -ne 0 ] && echo "âŒ Lint errors found." && exit 1

npx vitest run
[ $? -ne 0 ] && echo "âŒ Tests failed." && exit 1

echo "âœ“ All checks passed."`

const SETUP_GUIDE = `# SETUP GUIDE â€” claudemdforge.site

## 1 â€” Place files in your project
cp CLAUDE.md /your-project/CLAUDE.md
cp -r skills/ /your-project/.claude/skills/

## 2 â€” Enable the pre-commit hook (optional)
chmod +x hooks/pre-commit.sh
cp hooks/pre-commit.sh .git/hooks/pre-commit

## 3 â€” Open Claude Code
claude   # Claude Code auto-reads CLAUDE.md on every session

---
Generated by CLAUDE.md Forge â€” claudemdforge.site`

type Props = { result: ForgeResult }

function toSlug(title: string) {
  return title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') + '.md'
}

function colorLine(line: string): string {
  if (line.startsWith('#')) return '#E05C15'
  if (line.startsWith('-') || line.startsWith('*')) return '#A8D8A4'
  if (line.startsWith('â†’')) return '#7AB8F5'
  if (line.startsWith('[Source')) return '#777'
  return '#E6E4DC'
}

function CopyIcon() {
  return (
    <svg viewBox="0 0 24 24" width="13" height="13" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
      <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
    </svg>
  )
}

function SkillsModal({ skills, onClose }: { skills: Skill[]; onClose: () => void }) {
  const [selected, setSelected] = useState<Skill | null>(null)

  return createPortal(
    <div
      className="dialog-backdrop"
      onClick={onClose}
      style={{ alignItems: 'flex-start', paddingTop: 60 }}
    >
      <div
        className="dialog-panel"
        onClick={e => e.stopPropagation()}
        style={{ width: '100%', maxWidth: 720, maxHeight: '80vh', display: 'flex', flexDirection: 'column', padding: 0 }}
      >
        {/* Header */}
        <div style={{ padding: '20px 24px 16px', borderBottom: '1px solid var(--border)', display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexShrink: 0 }}>
          <div>
            <h2 style={{ fontFamily: 'var(--font-syne), Syne, sans-serif', fontWeight: 800, fontSize: 18, marginBottom: 2 }}>
              Selected Skills
            </h2>
            <p style={{ fontSize: 12.5, color: 'var(--muted)', margin: 0 }}>
              {skills.length} skills auto-selected for your stack
            </p>
          </div>
          <button
            onClick={onClose}
            style={{ background: 'transparent', border: '1px solid var(--border)', width: 32, height: 32, borderRadius: 8, cursor: 'pointer', fontSize: 18, color: 'var(--muted)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}
          >Ã—</button>
        </div>

        {/* Body â€” two-pane */}
        <div style={{ display: 'grid', gridTemplateColumns: '220px 1fr', flex: 1, minHeight: 0, overflow: 'hidden' }}>
          {/* skill list */}
          <div style={{ borderRight: '1px solid var(--border)', overflowY: 'auto', padding: '10px 0' }}>
            {skills.map(skill => (
              <button
                key={skill.id}
                onClick={() => setSelected(skill)}
                style={{
                  width: '100%', textAlign: 'left', padding: '10px 16px',
                  background: selected?.id === skill.id ? 'var(--orange-light)' : 'transparent',
                  borderLeft: `2px solid ${selected?.id === skill.id ? 'var(--orange)' : 'transparent'}`,
                  border: 'none', cursor: 'pointer', transition: 'background 0.12s',
                }}
              >
                <div style={{ fontSize: 9.5, fontFamily: 'var(--font-dm-mono), DM Mono, monospace', color: 'var(--orange)', textTransform: 'uppercase', letterSpacing: 1, marginBottom: 3 }}>
                  {skill.cat}
                </div>
                <div style={{ fontSize: 13, fontFamily: 'var(--font-syne), Syne, sans-serif', fontWeight: 700, color: 'var(--text)', lineHeight: 1.3 }}>
                  {skill.title}
                </div>
                <div style={{ fontSize: 11.5, color: 'var(--muted)', marginTop: 2 }}>
                  {skill.diff}
                </div>
              </button>
            ))}
          </div>

          {/* skill detail */}
          <div style={{ overflowY: 'auto', padding: '20px 24px' }}>
            {selected ? (
              <div>
                <span className="badge badge-cat" style={{ marginBottom: 10, display: 'inline-block' }}>{selected.cat}</span>
                <h3 style={{ fontFamily: 'var(--font-syne), Syne, sans-serif', fontWeight: 800, fontSize: 18, marginBottom: 10 }}>
                  {selected.title}
                </h3>
                <p style={{ fontSize: 13.5, color: 'var(--muted)', lineHeight: 1.7, marginBottom: 16 }}>
                  {selected.desc}
                </p>
                <div style={{ display: 'flex', flexWrap: 'wrap', gap: 5, marginBottom: 16 }}>
                  {selected.tags.map(t => <span key={t} className="tag">{t}</span>)}
                </div>
                <div className="mono" style={{ fontSize: 10, fontWeight: 700, letterSpacing: 1.5, color: 'var(--faint)', textTransform: 'uppercase', marginBottom: 8 }}>
                  // skill snippet
                </div>
                <div className="code-block" style={{ fontSize: 11.5 }}>{selected.snippet}</div>
              </div>
            ) : (
              <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '100%', gap: 10, color: 'var(--faint)', textAlign: 'center', padding: '40px 0' }}>
                <svg viewBox="0 0 24 24" width="32" height="32" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" opacity={0.4}>
                  <circle cx="12" cy="12" r="10" /><path d="M12 8v4M12 16h.01" />
                </svg>
                <p style={{ fontSize: 13, margin: 0 }}>Select a skill to see details</p>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>,
    document.body
  )
}

async function generateShareCaption(claudeMd: string, skills: ForgeResult['skills'], tags: string[]): Promise<string> {
  const res = await fetch('/api/test-drive', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      messages: [
        { role: 'system', content: 'You are a developer tweet writer. Generate a single engaging tweet (under 220 characters) for a developer who just generated a custom CLAUDE.md setup. Mention the stack/skills if interesting. Include #ClaudeCode at the end. Output ONLY the tweet text â€” no quotes, no preamble.' },
        { role: 'user', content: `Stack: ${tags.join(', ')}\nSkills: ${skills.map(s => s.title).join(', ')}\n\nCLAUDE.md preview:\n${claudeMd.slice(0, 500)}` },
      ],
    }),
  })
  const data = await res.json()
  return (data.content as string) ?? `Just forged my perfect CLAUDE.md with ${skills.length} skills for ${tags.slice(0, 2).join(' + ')} â€” claudemdforge.site #ClaudeCode`
}

type FileEntry = { id: string; icon: string; label: string; lang?: string; content: string }

export default function ResultPreview({ result }: Props) {
  const [activeId, setActiveId] = useState('claude-md')
  const [copied, setCopied] = useState(false)
  const [sharing, setSharing] = useState(false)
  const [skillsOpen, setSkillsOpen] = useState(false)

  const files: FileEntry[] = [
    { id: 'claude-md', icon: 'ðŸŸ ', label: 'CLAUDE.md', lang: 'markdown', content: result.claudeMd },
    ...result.skills.map(s => ({
      id: `skill-${s.id}`,
      icon: 'ðŸ“„',
      label: toSlug(s.title),
      lang: 'markdown',
      content: s.snippet,
    })),
    { id: 'hook', icon: 'ðŸ”§', label: 'pre-commit.sh', lang: 'bash', content: PRE_COMMIT_SH },
    { id: 'setup', icon: 'ðŸ“‹', label: 'SETUP_GUIDE.md', lang: 'markdown', content: SETUP_GUIDE },
  ]

  const active = files.find(f => f.id === activeId) ?? files[0]

  function downloadZip() {
    const url = URL.createObjectURL(result.zipBlob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'claude-forge-output.zip'
    a.click()
    URL.revokeObjectURL(url)
  }

  async function copyActive() {
    await navigator.clipboard.writeText(active.content)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  async function shareOnX() {
    setSharing(true)
    try {
      const caption = await generateShareCaption(result.claudeMd, result.skills, result.tags)
      window.open(`https://twitter.com/intent/tweet?text=${encodeURIComponent(caption + '\n\nclaudemdforge.site')}`, '_blank', 'noopener,noreferrer')
    } catch {
      const fallback = `Just forged my CLAUDE.md with ${result.skills.length} skills via claudemdforge.site â€” #ClaudeCode`
      window.open(`https://twitter.com/intent/tweet?text=${encodeURIComponent(fallback)}`, '_blank', 'noopener,noreferrer')
    } finally {
      setSharing(false)
    }
  }

  return (
    <div style={{ marginTop: 48 }}>

      {/* Success banner */}
      <div style={{
        display: 'flex', alignItems: 'center',
        padding: '14px 20px', marginBottom: 2,
        background: 'linear-gradient(135deg, #F0FDF4 0%, #ECFDF5 100%)',
        border: '1px solid #BBF7D0', borderRadius: '14px 14px 0 0',
        flexWrap: 'wrap', gap: 10,
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <div style={{ width: 8, height: 8, borderRadius: '50%', background: '#22C55E', boxShadow: '0 0 0 3px rgba(34,197,94,0.2)' }} />
          <span style={{ fontFamily: 'var(--font-syne), Syne, sans-serif', fontWeight: 700, fontSize: 13.5, color: '#15803D' }}>
            Forge complete
          </span>
        </div>
        <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', alignItems: 'center' }}>
          <span className="mono" style={{ fontSize: 11, padding: '3px 9px', borderRadius: 5, background: '#DCFCE7', border: '1px solid #86EFAC', color: '#15803D' }}>
            {files.length} files
          </span>
          <button
            className="mono"
            onClick={() => setSkillsOpen(true)}
            style={{
              fontSize: 11, padding: '3px 9px', borderRadius: 5,
              background: '#EFF6FF', border: '1px solid #93C5FD', color: '#1D4ED8',
              cursor: 'pointer', transition: 'all 0.15s', display: 'inline-flex', alignItems: 'center', gap: 4,
            }}
            onMouseOver={e => { (e.currentTarget).style.background = '#DBEAFE'; (e.currentTarget).style.borderColor = '#60A5FA' }}
            onMouseOut={e => { (e.currentTarget).style.background = '#EFF6FF'; (e.currentTarget).style.borderColor = '#93C5FD' }}
          >
            {result.skills.length} skills
            <svg viewBox="0 0 24 24" width="10" height="10" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
              <polyline points="6 9 12 15 18 9" />
            </svg>
          </button>
          {result.tags.slice(0, 3).map(t => (
            <span key={t} className="mono" style={{ fontSize: 11, padding: '3px 9px', borderRadius: 5, background: 'var(--orange-light)', border: '1px solid var(--orange-border)', color: 'var(--orange)' }}>{t}</span>
          ))}
        </div>
        <div style={{ flex: 1 }} />
        <div style={{ display: 'flex', gap: 8 }}>
          <button className="btn-dark" onClick={copyActive} style={{ display: 'inline-flex', alignItems: 'center', gap: 6 }}>
            {copied ? (
              <>
                <svg viewBox="0 0 24 24" width="13" height="13" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12" /></svg>
                Copied
              </>
            ) : (
              <>
                <CopyIcon />
                Copy {active.label}
              </>
            )}
          </button>
          <button className="btn-primary" style={{ fontSize: 13, padding: '9px 18px' }} onClick={downloadZip}>
            â¬‡ Download ZIP
          </button>
        </div>
      </div>

      {/* IDE layout */}
      <div style={{
        display: 'grid', gridTemplateColumns: '220px 1fr',
        border: '1px solid #2A2A24', borderTop: 'none',
        borderRadius: '0 0 14px 14px', overflow: 'hidden',
        background: '#141410',
        minHeight: 440,
      }}>
        {/* File tree sidebar */}
        <div style={{ borderRight: '1px solid #2A2A24', background: '#1A1A15' }}>
          {/* Folder headers */}
          {[
            { label: 'claude-forge-output/', items: files.filter(f => f.id === 'claude-md') },
            { label: 'skills/', items: files.filter(f => f.id.startsWith('skill-')) },
            { label: 'hooks/', items: files.filter(f => f.id === 'hook') },
            { label: '', items: files.filter(f => f.id === 'setup') },
          ].map(group => (
            <div key={group.label}>
              {group.label && (
                <div style={{
                  padding: '7px 14px 4px',
                  fontSize: 10.5,
                  fontFamily: 'var(--font-dm-mono), DM Mono, monospace',
                  color: 'var(--faint)',
                  letterSpacing: 0.5,
                  userSelect: 'none',
                }}>
                  {group.label}
                </div>
              )}
              {group.items.map(f => (
                <button
                  key={f.id}
                  onClick={() => setActiveId(f.id)}
                  style={{
                    width: '100%', textAlign: 'left',
                    padding: '7px 14px 7px 22px',
                    display: 'flex', alignItems: 'center', gap: 7,
                    background: activeId === f.id ? '#252520' : 'transparent',
                    borderLeft: activeId === f.id ? '2px solid var(--orange)' : '2px solid transparent',
                    border: 'none', cursor: 'pointer', transition: 'background 0.12s',
                    fontFamily: 'var(--font-dm-mono), DM Mono, monospace',
                    fontSize: 12, color: activeId === f.id ? '#FAFAF7' : '#666',
                    whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis',
                  }}
                >
                  <span style={{ fontSize: 13 }}>{f.icon}</span>
                  <span style={{ overflow: 'hidden', textOverflow: 'ellipsis' }}>{f.label}</span>
                </button>
              ))}
            </div>
          ))}
        </div>

        {/* Content pane */}
        <div style={{ display: 'flex', flexDirection: 'column', minWidth: 0 }}>
          {/* Tab bar */}
          <div style={{
            display: 'flex', alignItems: 'center', gap: 0,
            borderBottom: '1px solid #2A2A24', background: '#1A1A15',
            padding: '0 16px', height: 36, flexShrink: 0,
          }}>
            <span style={{ fontSize: 12, fontFamily: 'var(--font-dm-mono), DM Mono, monospace', color: '#888' }}>
              {active.icon} {active.label}
            </span>
            {active.lang && (
              <span className="mono" style={{ marginLeft: 'auto', fontSize: 10, color: '#555', background: '#252520', padding: '2px 7px', borderRadius: 4 }}>
                {active.lang}
              </span>
            )}
          </div>

          {/* Code area */}
          <div style={{ flex: 1, overflow: 'auto', padding: '18px 22px', background: '#141410' }}>
            {active.id === 'claude-md' ? (
              <div style={{ fontFamily: 'var(--font-dm-mono), DM Mono, monospace', fontSize: 12.5, lineHeight: 1.85, whiteSpace: 'pre-wrap' }}>
                {result.claudeMd.split('\n').map((line, i) => (
                  <div key={i} style={{ color: colorLine(line) }}>{line || 'Â '}</div>
                ))}
              </div>
            ) : (
              <pre style={{
                fontFamily: 'var(--font-dm-mono), DM Mono, monospace',
                fontSize: 12.5, lineHeight: 1.85, margin: 0,
                color: '#D4D2C9', whiteSpace: 'pre-wrap', wordBreak: 'break-word',
              }}>
                {active.content}
              </pre>
            )}
          </div>

          {/* Status bar */}
          <div style={{
            borderTop: '1px solid #2A2A24', background: '#0F0F0C',
            padding: '5px 16px', display: 'flex', alignItems: 'center', gap: 16, flexShrink: 0,
          }}>
            <span className="mono" style={{ fontSize: 10.5, color: '#444' }}>
              {active.content.split('\n').length} lines
            </span>
            <span className="mono" style={{ fontSize: 10.5, color: '#444' }}>
              {(active.content.length / 1024).toFixed(1)} kb
            </span>
            <div style={{ flex: 1 }} />
            <span className="mono" style={{ fontSize: 10.5, color: '#444' }}>
              UTF-8 · {active.lang ?? 'plaintext'}
            </span>
          </div>
        </div>
      </div>

      {skillsOpen && <SkillsModal skills={result.skills} onClose={() => setSkillsOpen(false)} />}

      {/* Share strip */}
      <div className="share-box" style={{ marginTop: 16 }}>
        <span style={{ fontSize: 18, fontWeight: 700, fontFamily: 'serif' }}>ð•</span>
        <div style={{ flex: 1 }}>
          <div style={{ fontSize: 13.5, fontWeight: 600, marginBottom: 2 }}>Share your forge</div>
          <div style={{ fontSize: 12.5, color: '#888' }}>
            {sharing ? 'Claude is writing your tweetâ€¦' : 'Claude writes a custom caption from your CLAUDE.md â€” every share helps.'}
          </div>
        </div>
        <button
          className="btn-outline"
          style={{ fontSize: 13, padding: '9px 18px', whiteSpace: 'nowrap', opacity: sharing ? 0.6 : 1 }}
          onClick={shareOnX}
          disabled={sharing}
        >
          {sharing ? 'Generatingâ€¦' : 'Share on X â†’'}
        </button>
      </div>
    </div>
  )
}
