import { zipSync, strToU8 } from 'fflate'
import { Skill } from './skills'

const PRE_COMMIT_SH = `#!/bin/bash
# pre-commit.sh — Generated by CLAUDE.md Forge — claudemdforge.site

echo "🔨 Running pre-commit quality checks..."

npx tsc --noEmit
[ $? -ne 0 ] && echo "❌ TypeScript errors found." && exit 1

npx eslint . --ext .ts,.tsx --max-warnings 0
[ $? -ne 0 ] && echo "❌ Lint errors found." && exit 1

npx vitest run
[ $? -ne 0 ] && echo "❌ Tests failed." && exit 1

echo "✓ All checks passed."
`

function toSetupGuide(skills: Skill[]): string {
  const fileList = skills.map(s => `# skills/${titleToFilename(s.title)}`).join('\n')
  return `# SETUP GUIDE — claudemdforge.site

## 1 — Place files in your project
cp CLAUDE.md /your-project/CLAUDE.md
cp -r skills/ /your-project/.claude/skills/

## 2 — Enable the pre-commit hook (optional)
chmod +x hooks/pre-commit.sh
cp hooks/pre-commit.sh .git/hooks/pre-commit

## 3 — Open Claude Code
claude   # Claude Code auto-reads CLAUDE.md on every session

# Files in this ZIP:
# CLAUDE.md              ← main AI context file
${fileList}
# hooks/pre-commit.sh   ← quality gate automation
# SETUP_GUIDE.md        ← this file

---
Generated by CLAUDE.md Forge — claudemdforge.site`
}

function titleToFilename(title: string): string {
  return title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') + '.md'
}

function skillToMarkdown(skill: Skill): string {
  return `# ${skill.title}

**Category:** ${skill.cat}
**Difficulty:** ${skill.diff}
**Tags:** ${skill.tags.join(', ')}

## Description

${skill.desc}

## Skill Content

${skill.snippet}

---
Generated by CLAUDE.md Forge — claudemdforge.site
`
}

export function buildZip(claudeMd: string, skills: Skill[]): Buffer {
  const files: Record<string, Uint8Array> = {
    'claude-forge-output/CLAUDE.md': strToU8(claudeMd),
    'claude-forge-output/hooks/pre-commit.sh': strToU8(PRE_COMMIT_SH),
    'claude-forge-output/SETUP_GUIDE.md': strToU8(toSetupGuide(skills)),
  }

  for (const skill of skills) {
    files[`claude-forge-output/skills/${titleToFilename(skill.title)}`] = strToU8(skillToMarkdown(skill))
  }

  const zipped = zipSync(files, { level: 6 })
  return Buffer.from(zipped)
}
