import { Skill } from './skills'

const SYSTEM_PROMPT = `You are an expert Claude Code setup generator.
Generate a CLAUDE.md file for the following project.

Base Core Principles on Andrej Karpathy's philosophy:
- Write code that reads like prose
- Prefer explicit over implicit
- Every function does exactly one thing
- Think in systems, not individual files
- Document the WHY not the WHAT

Detected stack: {tags}
Selected skills: {skillNames}

Output ONLY the CLAUDE.md content. No preamble. Use plain ASCII text only - no curly quotes, no em/en dashes, no non-breaking spaces.
End with: ---
Generated by CLAUDE.md Forge - claudemdforge.site`

export async function callClaude(stackContext: string, selectedSkills: Skill[]): Promise<string> {
  const apiKey = process.env.OPENROUTER_API_KEY
  if (!apiKey) throw new Error('OPENROUTER_API_KEY is not set')

  const tags = selectedSkills
    .flatMap(s => s.tags)
    .filter((t, i, a) => t !== 'universal' && a.indexOf(t) === i)
    .join(', ')
  const skillNames = selectedSkills.map(s => s.title).join(', ')

  const systemPrompt = SYSTEM_PROMPT
    .replace('{tags}', tags || 'general')
    .replace('{skillNames}', skillNames)

  const response = await fetch('https://openrouter.ai/api/v1/chat/completions', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${apiKey}`,
      'Content-Type': 'application/json',
      'HTTP-Referer': 'https://claudemdforge.site',
      'X-Title': 'CLAUDE.md Forge',
    },
    body: JSON.stringify({
      model: 'mistralai/ministral-3b-2512',
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: `Project context:\n\n${stackContext}` },
      ],
      max_tokens: 2000,
    }),
  })

  if (!response.ok) {
    const errorText = await response.text()
    throw new Error(`API error ${response.status}: ${errorText}`)
  }

  const data = await response.json()
  const content: string | undefined = data.choices?.[0]?.message?.content
  if (!content) throw new Error('Empty response from model')
  return sanitizeContent(content)
}

function sanitizeContent(text: string): string {
  return text
    .replace(/Â /g, '\n')
    .replace(/Â /g, '')
    .replace(/Â/g, '')
    .replace(/ /g, ' ')
    .replace(/â/g, "'")
    .replace(/â/g, '"')
    .replace(/â/g, '"')
    .replace(/â/g, '-')
    .replace(/â/g, '--')
    .replace(/â/g, '->')
    .replace(/\n{3,}/g, '\n\n')
    .trim()
}