import Anthropic from '@anthropic-ai/sdk'
import { Skill } from './skills'

const client = new Anthropic()

const SYSTEM_PROMPT = `You are an expert Claude Code setup generator.
Generate a CLAUDE.md file for the following project.

Base Core Principles on Andrej Karpathy's philosophy:
- Write code that reads like prose
- Prefer explicit over implicit
- Every function does exactly one thing
- Think in systems, not individual files
- Document the WHY not the WHAT

Detected stack: {tags}
Selected skills: {skillNames}

Output ONLY the CLAUDE.md content. No preamble.
End with: ---
Generated by CLAUDE.md Forge — claudemdforge.site`

export async function callClaude(stackContext: string, selectedSkills: Skill[]): Promise<string> {
  const tags = selectedSkills.flatMap(s => s.tags).filter((t, i, a) => t !== 'universal' && a.indexOf(t) === i).join(', ')
  const skillNames = selectedSkills.map(s => s.title).join(', ')

  const systemPrompt = SYSTEM_PROMPT
    .replace('{tags}', tags || 'general')
    .replace('{skillNames}', skillNames)

  const message = await client.messages.create({
    model: 'claude-sonnet-4-20250514',
    max_tokens: 2000,
    system: systemPrompt,
    messages: [
      {
        role: 'user',
        content: `Project context:\n\n${stackContext}`,
      },
    ],
  })

  const block = message.content[0]
  if (block.type !== 'text') throw new Error('Unexpected response type')
  return block.text
}
