export type Skill = {
  id: number
  title: string
  cat: string
  diff: 'beginner' | 'intermediate' | 'advanced'
  tags: string[]
  desc: string
  snippet: string
}

export const SKILLS: Skill[] = [
  {id:1,title:"Clean Code Principles",cat:"Code Quality",diff:"beginner",tags:["universal"],desc:"Enforce readable, maintainable code with naming conventions, function size limits, and cognitive complexity guidance.",snippet:"## Clean Code Standards\n- Max 20 lines per function\n- Descriptive naming: verbs for functions, nouns for vars\n- No magic numbers — use named constants\n- Single responsibility per module"},
  {id:2,title:"Code Review Checklist",cat:"Code Quality",diff:"beginner",tags:["universal"],desc:"Structured checklist covering correctness, security, performance, and readability.",snippet:"## Review Checklist\n- [ ] Logic correctness verified\n- [ ] Edge cases handled\n- [ ] No security vulnerabilities\n- [ ] Tests added/updated\n- [ ] Docs updated if API changed"},
  {id:3,title:"Error Handling Patterns",cat:"Code Quality",diff:"intermediate",tags:["universal"],desc:"Consistent error handling strategies with proper logging and user-facing messages.",snippet:"## Error Handling\n- Never swallow errors silently\n- Use typed errors (Result<T,E> or custom)\n- Log with context: what failed, why, recovery path\n- User errors: friendly; dev errors: full trace"},
  {id:4,title:"Naming Conventions",cat:"Code Quality",diff:"beginner",tags:["universal"],desc:"Project-wide naming rules for files, functions, variables, constants, and types.",snippet:"## Naming Rules\n- camelCase: variables, functions\n- PascalCase: classes, components, types\n- SCREAMING_SNAKE: env vars and constants\n- kebab-case: file names and CSS classes"},
  {id:5,title:"Refactoring Strategies",cat:"Code Quality",diff:"intermediate",tags:["universal"],desc:"Safe, incremental refactoring patterns with clear criteria for when to refactor vs rewrite.",snippet:"## When to Refactor\n- Duplication >3x or function >30 lines\n- Always refactor with tests in place first\n- One refactor per commit — keep diffs small\n- Strangler fig for large rewrites"},
  {id:6,title:"SOLID Principles",cat:"Code Quality",diff:"intermediate",tags:["oop","typescript","python"],desc:"Applied SOLID with concrete examples tailored to your language and architecture.",snippet:"## SOLID Applied\n- Single Responsibility: one class, one change reason\n- Open/Closed: extend via composition\n- Liskov: subtypes honour parent contracts\n- Dependency Inversion: depend on abstractions"},
  {id:7,title:"DRY & YAGNI",cat:"Code Quality",diff:"beginner",tags:["universal"],desc:"Don't Repeat Yourself and You Aren't Gonna Need It — preventing over-engineering.",snippet:"## DRY & YAGNI\n- Extract after 3rd duplication, not before\n- Don't add features 'just in case'\n- Premature abstraction is as bad as duplication\n- Inline > abstract when logic is similar but not identical"},
  {id:8,title:"Code Documentation",cat:"Code Quality",diff:"beginner",tags:["universal"],desc:"JSDoc/docstring standards, inline comment rules, and README structure.",snippet:"## Documentation Standards\n- Every public function: purpose, params, return, example\n- Inline comments: explain WHY, not WHAT\n- README: setup (5 min), usage, architecture\n- Keep docs co-located with code"},
  {id:9,title:"Conventional Commits",cat:"Git",diff:"beginner",tags:["universal"],desc:"Enforce conventional commit format enabling automated changelogs and semantic versioning.",snippet:"## Commit Format\nfeat: add user authentication\nfix: resolve memory leak in cache module\ndocs: update REST API reference\nchore: upgrade dependencies\n\nWith scope: feat(auth): add OAuth2 provider"},
  {id:10,title:"Branch Naming Strategy",cat:"Git",diff:"beginner",tags:["universal"],desc:"Consistent branch naming patterns that integrate cleanly with issue trackers and CI/CD.",snippet:"## Branch Naming\nfeature/ISSUE-123-user-authentication\nbugfix/ISSUE-456-login-redirect\nrelease/v2.1.0\nhotfix/critical-payment-bug"},
  {id:11,title:"Pull Request Best Practices",cat:"Git",diff:"beginner",tags:["universal"],desc:"PR size limits, description templates, review etiquette, and merge strategies.",snippet:"## PR Standards\n- Max 400 lines per PR (aim for 200)\n- Template: what changed, why, how to test\n- No self-merges without review\n- Squash merge to keep history clean"},
  {id:12,title:"Semantic Versioning",cat:"Git",diff:"beginner",tags:["universal"],desc:"SemVer rules and communicating breaking changes clearly.",snippet:"## SemVer: MAJOR.MINOR.PATCH\n- MAJOR: breaking API changes\n- MINOR: new backwards-compatible features\n- PATCH: backwards-compatible fixes\n- Pre-release: 1.0.0-beta.1"},
  {id:13,title:"Trunk-Based Development",cat:"Git",diff:"intermediate",tags:["universal"],desc:"Trunk-based development with feature flags and short-lived branches.",snippet:"## Trunk-Based Dev\n- Short-lived branches (<2 days)\n- Feature flags for incomplete work\n- Deploy from main continuously\n- Merge at least once per day"},
  {id:14,title:"Unit Testing Patterns",cat:"Testing",diff:"beginner",tags:["universal"],desc:"Arrange-Act-Assert, test naming, isolation principles, and coverage targets.",snippet:"## Unit Test Standards\n- AAA pattern: Arrange, Act, Assert\n- Name: should_[expected]_when_[condition]\n- One assertion focus per test\n- No network/DB calls in unit tests"},
  {id:15,title:"Integration Testing",cat:"Testing",diff:"intermediate",tags:["universal"],desc:"Testing service interactions, database operations, and API contracts.",snippet:"## Integration Tests\n- Use test containers for DB/services\n- Test happy path + all error paths\n- Seed data setup/teardown per suite\n- Max 2s per test"},
  {id:16,title:"E2E Testing (Playwright)",cat:"Testing",diff:"intermediate",tags:["playwright","nextjs","frontend"],desc:"End-to-end testing with Playwright: selectors, wait strategies, CI configuration.",snippet:"## E2E with Playwright\n- Use data-testid for all selectors\n- Avoid CSS/XPath selectors\n- Always await — no manual waits\n- Run in CI against preview deploy"},
  {id:17,title:"Test-Driven Development",cat:"Testing",diff:"intermediate",tags:["universal"],desc:"Red-Green-Refactor cycle and how to integrate AI into the TDD workflow.",snippet:"## TDD Cycle\n1. Write failing test (RED)\n2. Write minimal code to pass (GREEN)\n3. Refactor with tests passing (REFACTOR)\n- Apply to: business logic, algorithms"},
  {id:18,title:"Mocking & Stubbing",cat:"Testing",diff:"intermediate",tags:["universal"],desc:"When to mock vs. use real implementations, and avoiding over-mocking.",snippet:"## Mocking Rules\n- Mock external services, not internal logic\n- Use factory functions for test data\n- Avoid mocking what you don't own\n- Reset mocks between tests"},
  {id:19,title:"Test Coverage Goals",cat:"Testing",diff:"beginner",tags:["universal"],desc:"Meaningful coverage targets by code type and what coverage doesn't tell you.",snippet:"## Coverage Targets\n- Business logic: 90%+\n- Utilities & helpers: 95%+\n- UI components: 70%+\n- Coverage ≠ quality — test behaviour, not lines"},
  {id:20,title:"Snapshot Testing",cat:"Testing",diff:"beginner",tags:["react","frontend"],desc:"When snapshots help vs. hurt for UI components.",snippet:"## Snapshot Guidelines\n- Use for stable presentational components only\n- Always review diffs in PRs carefully\n- Avoid for data-heavy or dynamic components\n- Delete outdated snapshots aggressively"},
  {id:21,title:"React Component Patterns",cat:"React / Frontend",diff:"intermediate",tags:["react","nextjs","typescript"],desc:"Composition patterns, compound components, and when to use each approach.",snippet:"## React Patterns\n- Prefer composition over inheritance\n- Container/Presentational separation\n- Compound components for related UI groups\n- Custom hooks for all reusable logic"},
  {id:22,title:"State Management Strategy",cat:"React / Frontend",diff:"intermediate",tags:["react","nextjs"],desc:"Decision tree for local state vs. Zustand vs. TanStack Query.",snippet:"## State Decision Tree\n- UI state: useState/useReducer\n- Shared client state: Zustand\n- Server/async state: TanStack Query\n- Form state: React Hook Form\n- URL state: nuqs"},
  {id:23,title:"Next.js App Router",cat:"React / Frontend",diff:"intermediate",tags:["nextjs","react"],desc:"App Router patterns: server/client components, layouts, route handlers, metadata API.",snippet:"## Next.js App Router\n- Default to Server Components\n- 'use client' only when needed\n- Co-locate page-specific components\n- Route handlers for all API logic"},
  {id:24,title:"Tailwind Design System",cat:"React / Frontend",diff:"beginner",tags:["tailwind","react","nextjs"],desc:"Tailwind config conventions, custom tokens, and component class patterns.",snippet:"## Tailwind Conventions\n- Extract to components, not @apply\n- Use cn() for conditional classes\n- Define all colors in tailwind.config\n- Never use arbitrary values for brand colors"},
  {id:25,title:"Accessibility (a11y)",cat:"React / Frontend",diff:"intermediate",tags:["frontend","react"],desc:"WCAG 2.1 AA compliance, semantic HTML, ARIA usage, and keyboard navigation.",snippet:"## Accessibility Rules\n- Semantic HTML first, ARIA as last resort\n- All interactive elements keyboard accessible\n- Colour contrast min 4.5:1\n- Always: alt text, aria-labels, focus indicators"},
  {id:26,title:"Web Performance",cat:"React / Frontend",diff:"advanced",tags:["nextjs","react","frontend"],desc:"Core Web Vitals targets, image optimisation, bundle analysis, lazy loading.",snippet:"## Performance Targets\n- LCP < 2.5s, FID < 100ms, CLS < 0.1\n- Images: next/image with proper sizes\n- Bundle: @next/bundle-analyzer\n- Lazy load all below-fold components"},
  {id:27,title:"CSS Architecture",cat:"React / Frontend",diff:"intermediate",tags:["frontend"],desc:"CSS Modules vs. Tailwind vs. CSS-in-JS decision guide and global style management.",snippet:"## CSS Strategy\n- Tailwind for utility-first styling\n- CSS Modules for complex component styles\n- CSS variables for all design tokens\n- No inline styles except dynamic values"},
  {id:28,title:"Component Library Setup",cat:"React / Frontend",diff:"intermediate",tags:["react","nextjs","tailwind"],desc:"shadcn/ui integration, component variants with cva(), and Storybook docs.",snippet:"## Component Library\n- Base: shadcn/ui (copy-paste, fully owned)\n- Variants via cva() pattern\n- Document all variants in Storybook\n- Barrel export from /components/ui/"},
  {id:29,title:"TypeScript Strict Mode",cat:"TypeScript",diff:"intermediate",tags:["typescript"],desc:"Strict TypeScript config, rules to enforce, and common strict mode pitfalls.",snippet:"## TypeScript Config\n{\n  strict: true,\n  noUncheckedIndexedAccess: true,\n  exactOptionalPropertyTypes: true\n}\n- No 'any' — use 'unknown' + type guards"},
  {id:30,title:"Type Design Patterns",cat:"TypeScript",diff:"advanced",tags:["typescript"],desc:"Discriminated unions, branded types, utility types that prevent bugs at compile time.",snippet:"## Type Design\n- Discriminated unions for state machines\n- Branded: type UserId = string & {_brand:'UserId'}\n- Prefer interfaces for objects, types for unions\n- Use satisfies operator for inference + checking"},
  {id:31,title:"Generics Best Practices",cat:"TypeScript",diff:"advanced",tags:["typescript"],desc:"When to use generics, constraints, inference, and avoiding over-generic code.",snippet:"## Generics Rules\n- Use when logic applies to multiple types\n- Always constrain: <T extends object>\n- Let TypeScript infer where possible\n- Naming: T (type), K (key), V (value), E (element)"},
  {id:32,title:"Zod Schema Validation",cat:"TypeScript",diff:"intermediate",tags:["typescript","nextjs"],desc:"Zod schema patterns for API inputs, form validation, and env variable parsing.",snippet:"## Zod Patterns\n- Validate all external data at system boundaries\n- Co-locate schema with type definition\n- Use z.infer<typeof Schema> for derived types\n- Validate all env vars at startup"},
  {id:33,title:"Python Style Guide",cat:"Python",diff:"beginner",tags:["python"],desc:"PEP 8+ rules via Ruff, Google-style docstrings, consistent project structure.",snippet:"## Python Style\n- Formatter: ruff format\n- Linter: ruff check\n- Line length: 100 characters\n- Docstrings: Google style\n- Imports: stdlib → third-party → local"},
  {id:34,title:"Python Type Hints",cat:"Python",diff:"intermediate",tags:["python"],desc:"Full type annotation coverage with mypy strict mode.",snippet:"## Type Hints\n- All function signatures annotated\n- from __future__ import annotations\n- mypy config: strict = true\n- TypedDict for structured dicts\n- Protocol for structural subtyping"},
  {id:35,title:"Async/Await Patterns",cat:"Python",diff:"intermediate",tags:["python","fastapi"],desc:"asyncio patterns, FastAPI async conventions, and how to test async code.",snippet:"## Async Python\n- asyncio.gather() for concurrent tasks\n- Never block event loop\n- Test with pytest-asyncio\n- Timeout all external calls"},
  {id:36,title:"CLI with Typer",cat:"Python",diff:"intermediate",tags:["python","cli"],desc:"Production-grade CLIs with Typer: commands, options, Rich output.",snippet:"## Typer CLI\n- Rich for terminal output\n- Typer for argument parsing\n- Group commands by domain\n- Always write comprehensive --help\n- Package for pipx distribution"},
  {id:37,title:"Dependency Management (uv)",cat:"Python",diff:"beginner",tags:["python"],desc:"Modern Python dependency management with uv: lockfiles, virtual envs.",snippet:"## uv Dependency Management\n- uv.lock committed for reproducibility\n- Dev deps in [dependency-groups] dev\n- Never pin versions manually\n- uv run for one-off scripts"},
  {id:38,title:"REST API Design",cat:"Backend / API",diff:"intermediate",tags:["api","backend"],desc:"Resource naming, HTTP methods, status codes, pagination, and versioning.",snippet:"## REST Conventions\n- Resources: plural nouns (/users, /posts)\n- GET read, POST create, PATCH update\n- Status: 200 OK, 201 Created, 400 Bad, 404 Not Found\n- Pagination: cursor-based"},
  {id:39,title:"GraphQL Patterns",cat:"Backend / API",diff:"advanced",tags:["graphql","api"],desc:"Schema design, DataLoader for N+1, subscriptions.",snippet:"## GraphQL Conventions\n- Always DataLoader for batching (N+1 fix)\n- Schema-first — generate types from schema\n- Mutations always return modified resource\n- Errors in data field, not HTTP 4xx"},
  {id:40,title:"Auth & Authorization",cat:"Backend / API",diff:"advanced",tags:["api","security","backend"],desc:"JWT patterns, session management, RBAC, and authentication pitfalls.",snippet:"## Auth Patterns\n- JWTs: short-lived access + refresh rotation\n- Access in memory, refresh in httpOnly cookie\n- RBAC: roles in DB, permissions server-side\n- Never trust client claims"},
  {id:41,title:"API Rate Limiting",cat:"Backend / API",diff:"intermediate",tags:["api","backend"],desc:"Rate limiting strategies, response headers, user-friendly errors.",snippet:"## Rate Limiting\n- Headers: X-RateLimit-Limit, Remaining, Retry-After\n- Sliding window per IP + per auth user\n- 429 Too Many Requests with retry guidance\n- Whitelist: health check, webhook endpoints"},
  {id:42,title:"Database Query Patterns",cat:"Backend / API",diff:"intermediate",tags:["database","backend"],desc:"Prisma/SQLAlchemy conventions, N+1 prevention, migrations, transactions.",snippet:"## Database Conventions\n- ORM migrations only — no manual SQL changes\n- Select only fields you need\n- Wrap multi-step writes in transactions\n- Index: FK, filter, and sort fields"},
  {id:43,title:"API Error Standards",cat:"Backend / API",diff:"beginner",tags:["api","backend"],desc:"Consistent error response structure and machine-readable codes.",snippet:"## Error Response\n{\n  error: {\n    code: 'VALIDATION_ERROR',\n    message: 'Email is invalid',\n    details: [{field:'email',msg:'...'}],\n    requestId: 'req_abc123'\n  }\n}"},
  {id:44,title:"Webhook Handling",cat:"Backend / API",diff:"intermediate",tags:["api","backend"],desc:"Receiving webhooks securely: signature verification, idempotency.",snippet:"## Webhook Security\n- Verify HMAC signature before processing\n- Return 200 immediately, process async\n- Store event ID — reject duplicates\n- Retry with exponential backoff"},
  {id:45,title:"Docker Best Practices",cat:"DevOps",diff:"intermediate",tags:["docker","devops"],desc:"Multi-stage builds, image size optimisation, security hardening.",snippet:"## Docker Conventions\n- Multi-stage: builder → minimal runner\n- Non-root user in all prod images\n- .dockerignore: node_modules, .git, .env\n- Alpine or distroless base images"},
  {id:46,title:"CI/CD with GitHub Actions",cat:"DevOps",diff:"intermediate",tags:["github-actions","devops"],desc:"Workflows for lint, test, build, deploy with caching and matrix strategies.",snippet:"## GitHub Actions\n- Cache: node_modules, pip, cargo\n- Matrix: test across Node 18/20, Python 3.11/3.12\n- Deploy: only on main, only after all checks pass\n- Secrets: OIDC — never in code"},
  {id:47,title:"Environment Management",cat:"DevOps",diff:"beginner",tags:["devops"],desc:".env conventions, environment configs, and secret rotation.",snippet:"## Env Management\n- .env.example: all keys, no values, committed\n- .env: always in .gitignore\n- Validate all env vars at startup\n- Separate .env.test for tests"},
  {id:48,title:"Logging & Observability",cat:"DevOps",diff:"intermediate",tags:["devops","backend"],desc:"Structured JSON logging with pino/structlog, log levels, OpenTelemetry.",snippet:"## Logging Standards\n- Structured JSON logs in non-local envs\n- Levels: error (page me), warn, info\n- Always include: requestId, userId, timestamp\n- Never log passwords or PII"},
  {id:49,title:"Secrets Management",cat:"DevOps",diff:"advanced",tags:["security","devops"],desc:"Vault, AWS Secrets Manager, GitHub OIDC for zero-trust secret handling.",snippet:"## Secrets Rules\n- Never hardcode secrets, even in tests\n- Rotate on any team member departure\n- Use short-lived credentials and OIDC\n- Audit secret access monthly"},
  {id:50,title:"Project Structure",cat:"Architecture",diff:"beginner",tags:["universal"],desc:"Opinionated folder structure for different project types.",snippet:"## Next.js Structure\nsrc/\n  app/         # routes and pages\n  components/  # shared UI\n  lib/         # pure utilities\n  hooks/       # custom React hooks\n  types/       # shared TypeScript types\n  server/      # server-only code"},
  {id:51,title:"Monorepo Setup (Turborepo)",cat:"Architecture",diff:"advanced",tags:["monorepo","turborepo"],desc:"Turborepo configuration, workspace structure, shared packages.",snippet:"## Turborepo Structure\napps/\n  web/         # Next.js frontend\n  api/         # Fastify API\npackages/\n  ui/          # shared design system\n  config/      # eslint, tsconfig\n  types/       # shared types"},
  {id:52,title:"Caching Strategies",cat:"Architecture",diff:"advanced",tags:["backend","performance"],desc:"In-memory, Redis, CDN, and HTTP caching with clean invalidation.",snippet:"## Cache Strategy\n- In-memory: frequently read, rarely changed\n- Redis: distributed session + rate limits\n- CDN: all static assets\n- Cache-aside: read-through, write-through"},
  {id:53,title:"Security Checklist",cat:"Architecture",diff:"intermediate",tags:["security","universal"],desc:"OWASP Top 10 coverage, dependency auditing, security review.",snippet:"## Security Checklist\n- [ ] All inputs validated and sanitised\n- [ ] Parameterised queries everywhere\n- [ ] Output escaping for XSS\n- [ ] CSRF tokens on state-changing endpoints\n- [ ] npm audit in CI weekly"},
  {id:54,title:"Prompt Engineering",cat:"AI / LLM",diff:"intermediate",tags:["ai","llm"],desc:"System prompts, few-shot examples, chain-of-thought, and output formatting.",snippet:"## Prompt Patterns\n- System: role, rules, output format explicitly\n- Few-shot: 2-3 examples before the task\n- CoT trigger: 'think step by step'\n- Temperature: 0 for structured, 0.7+ for creative"},
  {id:55,title:"LLM Integration Patterns",cat:"AI / LLM",diff:"intermediate",tags:["ai","anthropic","typescript","python"],desc:"Anthropic SDK patterns, streaming, error handling, retry logic, cost management.",snippet:"## LLM Integration\n- Always stream for long generations\n- Exponential backoff for 429 errors\n- Estimate token budget before each call\n- Cache identical prompts aggressively\n- Log every call: model, tokens, cost, latency"},
  {id:56,title:"RAG Architecture",cat:"AI / LLM",diff:"advanced",tags:["ai","llm","vector-db"],desc:"Retrieval-Augmented Generation: chunking, embedding, retrieval, re-ranking.",snippet:"## RAG Pipeline\n1. Chunk: semantic, not fixed-size\n2. Embed: model matched to task\n3. Store: pgvector or Pinecone\n4. Retrieve: top-k with re-ranking\n5. Generate: retrieved context in system prompt"},
  {id:57,title:"Agent Design Patterns",cat:"AI / LLM",diff:"advanced",tags:["ai","agents","llm"],desc:"ReAct pattern, tool design, agent memory architecture, multi-agent orchestration.",snippet:"## Agent Patterns\n- ReAct: Reason → Act → Observe\n- Tools: narrow scope, clear descriptions\n- Memory: short-term (context), long-term (vector)\n- Always set max_iterations\n- Log every tool call"},
  {id:58,title:"MCP Server Integration",cat:"AI / LLM",diff:"advanced",tags:["mcp","claude-code","ai"],desc:"Building and integrating MCP servers with Claude Code.",snippet:"## MCP Integration\n- One MCP server per domain\n- Tool names: action_resource (create_task)\n- Return structured data, not prose\n- Handle errors in tool result content\n- Deploy independently from main app"},
  {id:59,title:"Karpathy Coding Principles",cat:"AI / LLM",diff:"beginner",tags:["universal","claude-code"],desc:"Andrej Karpathy's core coding philosophy adapted for Claude Code workflows.",snippet:"## Karpathy Principles\n- Think before you code: understand first\n- Write code that reads like English prose\n- Small, composable functions always\n- Prefer explicit over clever\n- Document the 'why', not the 'what'"},
]

export const CATEGORIES = ["All", ...([...new Set(SKILLS.map(s => s.cat))])]
